### ISSUE TITLE
为啥使用ubuntu-latest 环境的时候会提示找不到项目文件？项目文件明明就在的，而且大小写也已经检查过了。。。T-T

### ISSUE THREAD

**Issue by Lc3586** [SuperSocket/SuperSocket.JTT#4]
![image](https://user-images.githubusercontent.com/34331208/109587173-92beca80-7b41-11eb-98c8-3e4f9c544a68.png)

**Comment by kerryjiang** [comment]
我看你已经解决这个问题了？

**Comment by Lc3586** [comment]
> 我看你已经解决这个问题了？

还没有，之前运行成功是因为我暂时把ubuntu去掉了。这个问题我还没搞明白，得再研究研究。

**Comment by kerryjiang** [comment]
Just create nuget spec files outside the source code would be easier?

https://github.com/kerryjiang/SuperSocket/blob/master/pkg/SuperSocket.nuspec

**Comment by Lc3586** [comment]
> Just create nuget spec files outside the source code would be easier?
> 
> https://github.com/kerryjiang/SuperSocket/blob/master/pkg/SuperSocket.nuspec

Great! Its fixed,even I don't know why...

                                                     -from https://fanyi.baidu.com

**Comment by Lc3586** [comment]
问题已修复。
